name: Deploy to Production

on:
  push:
    branches: [ prod ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x' # Specify your .NET version

      - name: Publish application
        run: dotnet publish YourProjectName.csproj -c Release -o ./publish # Change YourProjectName

      - name: Deploy to Production Server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.PROD_HOST }}
          username: ${{ secrets.PROD_USERNAME }}
          key: ${{ secrets.PROD_SSH_KEY }}
          source: "./publish/*"
          target: "/var/www/prod-app" # Target directory for Production
          script: |
            echo "Deployment to PRODUCTION successful. Restarting service..."
            sudo systemctl restart your-prod-app-service # Your Production service name
