name: .NET Multi-Environment Deploy

on:
  # Trigger the workflow on pushes (merges) to these environment branches
  push:
    branches: [ "qa", "uat", "main" ]
  # Also trigger on pull requests to run tests before merging
  pull_request:
    branches: [ "qa", "uat", "main" ]

jobs:
  # =================================================================
  #  BUILD AND TEST JOB - Runs for every trigger
  # =================================================================
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'

      - name: Restore, Build, and Test
        run: |
          dotnet restore
          dotnet build --no-restore --configuration Release
          dotnet test --no-build --verbosity normal
      
      - name: Publish API
        run: dotnet publish --configuration Release --output ./publish
        
      - name: Upload artifact for deployment jobs
        uses: actions/upload-artifact@v4
        with:
          name: api-publish
          path: ./publish

  # =================================================================
  #  DEPLOY TO QA - Runs only on push to 'qa' branch
  # =================================================================
  deploy-to-qa:
    needs: build-and-test
    if: github.ref == 'refs/heads/qa' && github.event_name == 'push'
    runs-on: ubuntu-latest
    environment: 
      name: QA
      url: ${{ secrets.QA_URL }} # Optional: Add your QA site URL as a secret
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: api-publish
      - name: Deploy to QA Server
        run: echo "Deploying to QA..."
        # Example: uses: azure/webapps-deploy@v2
        # with:
        #   app-name: 'your-qa-app-name'
        #   publish-profile: ${{ secrets.AZURE_QA_PUBLISH_PROFILE }}

  # =================================================================
  #  DEPLOY TO UAT - Runs only on push to 'uat' branch
  # =================================================================
  deploy-to-uat:
    needs: build-and-test
    if: github.ref == 'refs/heads/uat' && github.event_name == 'push'
    runs-on: ubuntu-latest
    environment: 
      name: UAT
      url: ${{ secrets.UAT_URL }}
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: api-publish
      - name: Deploy to UAT Server
        run: echo "Deploying to UAT..."
        # Example: uses: azure/webapps-deploy@v2
        # with:
        #   app-name: 'your-uat-app-name'
        #   publish-profile: ${{ secrets.AZURE_UAT_PUBLISH_PROFILE }}

  # =================================================================
  #  DEPLOY TO PRODUCTION - Runs only on push to 'main' branch
  # =================================================================
  deploy-to-prod:
    needs: build-and-test
    if: github.ref == 'refs/heads/main' && github.event_name == 'push'
    runs-on: ubuntu-latest
    environment:
      name: Production
      url: ${{ secrets.PROD_URL }}
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: api-publish
      - name: Deploy to Production Server
        run: echo "Deploying to Production..."
        # Example: uses: azure/webapps-deploy@v2
        # with:
        #   app-name: 'your-prod-app-name'
        #   publish-profile: ${{ secrets.AZURE_PROD_PUBLISH_PROFILE }}
